### ISSUE TITLE
Use JWTs for user authorization and authentication

### ISSUE THREAD

**Issue by ChandradithyaJ** [ChandradithyaJ/Sankalp#2]

**Comment by cs21b037iittp** [comment]
done to test ppl plz refer to updates from now password being stored as hash and require to use token(jwt) for all secure req
EXCEPT LOGIN to implement after once seeing changes on users.js

**Comment by ChandradithyaJ** [comment]
fixed minor bugs, now refactoring

**Comment by ChandradithyaJ** [comment]
Tested all with Thunderclient. Need to implement on client side.
