### ISSUE TITLE
Find/Create 3 Stories

### ISSUE THREAD

**Issue by ChandradithyaJ** [ChandradithyaJ/Sankalp#26]

**Comment by cs21b037iittp** [comment]
in [doc](https://docs.google.com/document/d/1RqVprNgQPXJKD4kJbzo27Cb9ZkVWinfUNozuykPWJ0c/edit?usp=sharing)

**Comment by ChandradithyaJ** [comment]
Created 2 - 1 more to go.

**Comment by ChandradithyaJ** [comment]
Done. Just need to upload to Mongo.

**Comment by ChandradithyaJ** [comment]
Uploaded 2. Will add the last one tomorrow.

**Comment by ChandradithyaJ** [comment]
The third one is about PTSD.
