### ISSUE TITLE
UI updates for the News API

### ISSUE THREAD

**Issue by ChandradithyaJ** [ChandradithyaJ/Sankalp#8]

**Comment by arpitguptagithub** [comment]
UI update done, Bug for calls is there will check

**Comment by arpitguptagithub** [comment]
So api is limited, We crossed the benchmark of 1000 as of now. SO error of too many requests is poping up. Wait till 19 hours , we will use the api after or Will update with new account

**Comment by ChandradithyaJ** [comment]
Can you push the latest, or will you push after debugging?

**Comment by ChandradithyaJ** [comment]
Done.
